ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'SESSION_REVOKE';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'SESSION_REVOKE_ALL';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'SESSION_EXPIRE';
ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'SESSION_CLEANUP';
