import { Router } from "express";
import { ataItemsRoutes } from "./modules/ata-items/ata-items.routes.js";
import { atasRoutes } from "./modules/atas/atas.routes.js";
import { authRoutes } from "./modules/auth/auth.routes.js";
import { dashboardRoutes } from "./modules/dashboard/dashboard.routes.js";
import { estimatesRoutes } from "./modules/estimates/estimates.routes.js";
import { exportsRoutes } from "./modules/exports/exports.routes.js";
import { globalSearchRoutes } from "./modules/global-search/global-search.routes.js";
import { healthRoutes } from "./modules/health/health.routes.js";
import { openApiRoutes } from "./modules/openapi/openapi.routes.js";
import { operationalAlertsRoutes } from "./modules/operational-alerts/operational-alerts.routes.js";
import { projectsRoutes } from "./modules/projects/projects.routes.js";
import { permissionsRoutes } from "./modules/permissions/permissions.routes.js";
import { reportsRoutes } from "./modules/reports/reports.routes.js";
import { tasksRoutes } from "./modules/tasks/tasks.routes.js";
import { usersRoutes } from "./modules/users/users.routes.js";
import { diexRoutes } from "./modules/diex/diex.routes.js";
import { militaryOrganizationsRoutes } from "./modules/military-organizations/military-organizations.routes.js";
import { serviceOrdersRoutes } from "./modules/service-orders/service-orders.routes.js";

export const routes = Router();

routes.use("/health", healthRoutes);
routes.use("/docs", openApiRoutes);
routes.use("/auth", authRoutes);
routes.use("/users", usersRoutes);
routes.use("/projects", projectsRoutes);
routes.use("/permissions", permissionsRoutes);
routes.use("/tasks", tasksRoutes);
routes.use("/atas", atasRoutes);
routes.use("/ata-items", ataItemsRoutes);
routes.use("/estimates", estimatesRoutes);
routes.use("/dashboard", dashboardRoutes);
routes.use("/search", globalSearchRoutes);
routes.use("/operational-alerts", operationalAlertsRoutes);
routes.use("/exports", exportsRoutes);
routes.use("/reports", reportsRoutes);
routes.use("/diex", diexRoutes);
routes.use("/military-organizations", militaryOrganizationsRoutes);
routes.use("/service-orders", serviceOrdersRoutes);
