ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'ATA_ITEM';

ALTER TYPE "AuditActionType" ADD VALUE IF NOT EXISTS 'REGISTER_EXTERNAL_CONSUMPTION';

ALTER TYPE "AtaItemBalanceMovementType" ADD VALUE IF NOT EXISTS 'EXTERNAL_CONSUMPTION';
